---
- hosts: all
  become: true

  tasks:
  - name: get cpu metrics
    sensu_check:
      name: cpu_load
      command: /etc/sensu/plugins/system/cpu-mpstat-metrics.rb
      metric: yes
      handlers: relay
      subscribers: common
      interval: 60
